import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "../utils/api";
import { TestComponent } from "../components/TestComponent/Test";

const Home: NextPage = () => {
    const hello = api.example.hello.useQuery({ text: "from tRPC" });

    return (
        <>
            <TestComponent />
            <Head>
                <title>ELTE IK Progress Tracker</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
                <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
                    ELTE IK Progress Tracker is in works. Check back later.
                </h1>
            </main>
        </>
    );
};

export default Home;
